### ISSUE TITLE
It looks like multi-instance Protractor will fail-fast all running instances and it's a problem

### ISSUE THREAD

**Issue by NeverwinterMoon** [Updater/protractor-fail-fast#3] opened 2017-02-27 10:47 UTC
So, we have Protractor maxInstances set to 3, meaning we could have 3 specs running in parallel. Each spec, obviously, varies in length. So, if we launch all 3 at first, and one of the specs finishes early, another one takes its place while the other 2 continue running.

Now, with protractor-fail-fast it seems that if 1 out of 3 specs fails somewhere in the middle, it will fail the other 2 specs. Ideally, it would be that it fails fast 1 of 3 specs and exits the failed instance, so a next spec would take its place. Currently, it's a bit hard to look at the reports produced on failure - they mark only the spec that failed as a failure, but the other two (which were also halted) would be marked as skipped. This is a very stealthy behavior as we do have some other tests that are marked as skipped manually.

---
EDIT 1 

I may assume that this happens by design, but if it does, it's still not doing any good - it fails all simultaneously running instances, which just launches next instances in the queue - so it fails fast only on one slice of specs, not the whole batch.

I think this should either
* fail all the specs - running and queued (which it doesn't)
* fail only one spec (in our case the best scenario) as we don't want to continue running one spec after a single failure
* be configurable to use either first or second

---
EDIT 3

```
  postTest: function(passed) {
    if (!passed) {
      setFailed();
    }

    if (hasFailed()) {
      disableSpecs();
    }
  }
```

I assume this is the place that makes it happen. If one of the instances failed, it creates the file that is shared across instances and then disables all the remaining tests in concurrently running specs. Next batch of tests in queue will erase the existing file on disk and still continue running.

**Comment by pmowrer** [comment] 2017-03-14 20:45
Hi there! 

Failing multiple runners is essentially the entire reason for this project, but I understand it negatively impacts your scenario. We haven't run into it as we haven't used queued runners yet. Unfortunately, it isn't the easiest thing to solve for. The test runners are all independent and there aren't any Protractor hooks that help communicate between them (thereof the crude `.protractor-failed` file).

I don't think it'll fix the problem, but please give the latest version, `3.0.0.`, a try (and see README for updated/simpler configuration). 

If you have any ideas for approaches to the problem we're all ears!

**Comment by pmowrer** [comment] 2017-03-27 03:42
Closing as "by design". Please re-open if you have any ideas how to solve for your particular proble,

**Closed by pmowrer** 2017-03-27 03:42 UTC
